version: '3.9'
services:
  zoomcamp-pg-db:
    image: postgres:13.3
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=ny_taxi
    ports:
      - 5433:5432
    volumes:
      - "./ny_taxi_postgres_data:/var/lib/postgresql/data:rw"
  zoomcamp-pgadmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=root
    ports:
      - 8081:80